# Generated by Django 3.0.2 on 2020-03-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_popular',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Not', 'Not')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
