# Generated by Django 3.0.2 on 2020-03-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_events', '0002_auto_20200310_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
